language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2/repository"
sudo: false
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    on_success: never
    on_failure: always
install: true
branches:
  only:
  - master
script:
- mvn --settings .travis.settings.xml clean cobertura:cobertura deploy
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn --settings .travis.settings.xml site
env:
  global:
  - secure: wtPVzUiyaA2S/XENiOVyCyBVB4q6kitwmbituM9czInP/zgW3kHsipXcpGd207J3buZ0Ps+VZJMtg9s5s/p/l0sQUkzcPYsJTENAWK5fCdHg3wG3Et7qXH48nwdEOm74nQ/St1p4aEXxGiVTBGbWGa7LTwieyuHDPYiHMgnS0hC2HyUpn5pwOJ5rLlnOZ7Mt1+wjwpz54QagWC62M79VA4gFwJy+io7T09VeT5ap69yRzhJ5dmGbN5g/Kxj3q7NRVduzCXMLmNEjUibYtTwyHLCv1GUcwLmVDMR9Qws5SbwgRn9ck3Fs8t+euTKuAr8IpM0/4u4D4WCYXyanPWKfbuGLiSSK2pNxFq6Ih878mQyY5J5x4VDwympsr4/BVvet2gfNUaJW/YSER2oIbmCFNx/jfCdvQN/EnPnTvJxWoivFxU8r0ScOczp4GjZ4wps8mAr33EzDdXdZ2VDSkv4TNh2TjgkR+JMAyT2US9eIqSTJzLMVAkZdqkEim5jFfTGCcXQgcSFw3kliIlj4D1p4qtz8BJTABiVoWljvly8717e34euLs5ze0Dv4CqP7EB+y6Nqv/t4g9hv2CnHqYpkD/NtdyCgWhr99b7z7FaQ+5AfcXT8AahfIDIMV6kJ9oU5sN/nOt2FECoyIv2pZMNOiYdS648ZWXr+OZDySdHe/RUg=
  - secure: QCpd/QxCnml15EnbMbwBBabGV3rFLKEucOJ4pJ+ZgnPaMIBIHYzvgLyiuHrQqnRP3xYfbvazTJ8gnRk73J1OKpnZzqkmEJmq8YGn/fVuA3oMvTKsvfm5A8bxDPuK4Bzz+kJ6eQcxjQByBSvT92FZtkpwb1IMoct5C2yVhrEhbHysqOhZZHNDt8B2T1FLGcCBA+nDZVCvFbaxNbxJcFyIDnjUfA/5eWAaNKw+1EOwDaD3V9AYr/0+6AJPBaJxYllrfV44qY4K589z3UY5w2Kxodi7k3r5mJfnD726vp9hm38v/Y69of/Kpz4jWutMdRhvAuV82TAt+ipn/Egh7RCBi+gb+Bmnvg3P+k6+98XLLr4M8UYlKn5eR4ETgbCm83RvYsArIZc9LZMjRKW+GkGBxWFc45GnIVL+DGd0ap64Ak1MSGjfdguCBYD/vgpE/58R3sWV/2CwJzpsrc/UT/i+YWzJOHFZtIM28s/2FAqNUwInRVsy8exHfAoVFw1uqvQY+DvoUdnNETLEQuasTefN8skuDGTeS/FT1YL4yzht3PQM7syB+YkmGkAVH+wKy2XnKF1Ae4tYmdOIeqA4597A9V4FoQS3CUa0FVyNJP1cTtjvgnegkm3H1bLQgaQtg24rD9UsYh2X4+Eh9MkDR8m+/6IG5Rjbod4NwAxNSuufSh4=
  - secure: n+DNpod4gSQLbq1Ez5wOXv7ZMrJE9cTpyvznNyxFt6vukTWCYCrVr6WMPn2ZTbjdGQqkccIF35my2uYr9N4mEZknugOiX171jdLHtHHLtB7egCV2kgnDfJ0t2EWVry2plqns2Acy48BQB0a5UYhoGrtlwvxxHAM7K80OKLrlgstiKL5IticjpVRp0nptEmYreNOr6qFgMhZheN9YV1JB7ltpWy4uSBMz5aRWyWv9umgiTB260qOFU+xuR2pC47M1kjr4dQVms9zcPMlC4Yy8sGUCPYB7Nf7YvtPOz4alpmNtwRRTM3Qdk75K6TwOqV1pxbVyV+8rmECDUSYDyTL7OxRx+ejjxDSeYB8fhAs6ywucnn0gq/jP24hpDgpOZbQmyvJAIMldTCYoimeO9ue4v+C6FF3qMX49r3IVI4kFvFEEUShkIpYS+SfGsHW0CpI+gf7RiRYoZuMbvENCWnMzgqVgpM925DkyA4Qhnh3yaAfvqlAUvJ0ytPiHHDOlJhXU0xL8ydcUj8oWLs2eySs5Y/jeIkcD5RUqfcdGJaCR4uQPEvRyc5N2L1zbctAm/BLYAmOUQHsaPST5w+f3FUf9QucU1C61thSFJ9w9HPwoeX7TQS1nTb6xP/0g+zry9KXPmdKUFLR46FYxVcEqtmoZMchXdrQ45YPvwKzbFFFVz1o=
