sudo: false
dist: trusty
language: java
jdk: openjdk8
cache:
  directories:
  - "$HOME/.m2/repository"
branches:
  only:
  - master
  - development
before_install: unset _JAVA_OPTIONS
install: true
before_script: if [ "$VAADIN_CHARTS_LICENSE_CODE" != "" ]; then echo "$VAADIN_CHARTS_LICENSE_CODE"
  > ~/.vaadin.charts.developer.license; fi;
script: mvn --quiet --activate-profiles !development-build,!release-build --settings
  .travis.settings.xml clean cobertura:cobertura install
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn --quiet --activate-profiles !development-build,!release-build --settings .travis.settings.xml
  site
deploy:
- skip_cleanup: true
  provider: script
  script: mvn --quiet --activate-profiles development-build,!release-build --settings
    .travis.settings.xml deploy
  on:
    branch: development
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
- skip_cleanup: true
  provider: script
  script: mvn --quiet --activate-profiles !development-build,release-build --settings
    .travis.settings.xml deploy
  on:
    branch: master
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: lyFhOuYnDWmpxdSZJs6KzbXr+YcVRis4SpxGhZ9KAwhX1faW+ExtJPc5xfAHy5HwnQe/IVsHh2n4xFyBP7dwbQWeOe1QIxo/biftz51Thlig/nCuUIPq/qzpjFlIOYtzJZYArxmlLw4gZCilltExdzSJQjPv+OFSW26ss6F1aiDQRqTJjQIv/TmyrXKiZko56il1H6pcUeXImpRxR7uJXqTmP9stxbpLEc+qZWYVMe/aZWrv1ge/N1t1f7FMGK7XiSDnzdUgei00u6e/NAqdpSbHmt2mwVjZQAaxT64f0bACo3Ll30cmxsrkxXRN2tJ3dylnpq4THXCJN9F/lZcgBiq9NgxfzVKgzO2Kgxc5of//216o8L88/WiyEUdGDW+cmSscM0iGNsAcTRErZDRTfrf6jJ5RZu6za1NeQh+bvYCNBtjp1KETc7/J9hYfSZeoLc2OzYtOSPOzu7DqJW9haIfqWC3jWWEzgju50RDT4GCVfTCLA8XbQfzJI9hSE/r5Y42l7jKruxTP6SxfTBF4i+BHAm/qILXrMkjBsgrX0NVht68Ch+8MhvbuSPpPae0YOLyix6nhAnSvjEK0Q5HFXVIWah3koqQU59rwSH5MrJ5fyespmOgHgA2zIrfKvDzRrFPt/I+mMtono3d2kSDv90YdhgYPyQRKzKUUaMGgSJo=
env:
  global:
  - secure: wtPVzUiyaA2S/XENiOVyCyBVB4q6kitwmbituM9czInP/zgW3kHsipXcpGd207J3buZ0Ps+VZJMtg9s5s/p/l0sQUkzcPYsJTENAWK5fCdHg3wG3Et7qXH48nwdEOm74nQ/St1p4aEXxGiVTBGbWGa7LTwieyuHDPYiHMgnS0hC2HyUpn5pwOJ5rLlnOZ7Mt1+wjwpz54QagWC62M79VA4gFwJy+io7T09VeT5ap69yRzhJ5dmGbN5g/Kxj3q7NRVduzCXMLmNEjUibYtTwyHLCv1GUcwLmVDMR9Qws5SbwgRn9ck3Fs8t+euTKuAr8IpM0/4u4D4WCYXyanPWKfbuGLiSSK2pNxFq6Ih878mQyY5J5x4VDwympsr4/BVvet2gfNUaJW/YSER2oIbmCFNx/jfCdvQN/EnPnTvJxWoivFxU8r0ScOczp4GjZ4wps8mAr33EzDdXdZ2VDSkv4TNh2TjgkR+JMAyT2US9eIqSTJzLMVAkZdqkEim5jFfTGCcXQgcSFw3kliIlj4D1p4qtz8BJTABiVoWljvly8717e34euLs5ze0Dv4CqP7EB+y6Nqv/t4g9hv2CnHqYpkD/NtdyCgWhr99b7z7FaQ+5AfcXT8AahfIDIMV6kJ9oU5sN/nOt2FECoyIv2pZMNOiYdS648ZWXr+OZDySdHe/RUg=
  - secure: rxR/rjZfK8ZWCi+wzbJn6x4jgNfFav2bJHzLy1TGYLs3296/23KgUvCvmoFN1K8QHnd0o44sjFnFEO1okk5mcXd+Q5EJFpA6LcxPeMBdjFR3fxlS/ZWi9KIfJcmg2UZ4tUhGC4Jz2ZWSKtxGgugOIcBdYcQXMWLGr+8PS8D2I199/VsKzzayg1vPQSQm8dUgBDQnCmtkC6SsHSZfm7ctOm45nysHUSqtZKHIQldASQKz5PspjdThPBIJYtS/knVPzaDLOG9LJ13WCbajG/ft2ab9uqxcGlcR/pL+XtDidCq/9kQOaXYTbmEtnHeosdB8Zbyp9FN9vdBHT145jC98rZImYZPE7AohL1SRb0wtalD0pvK27aqLXpqgiHw4yOgFYGwjKXzySjNLE5YLCEO6mSBTcIKS4V1QXNE37Ic1JTdKoeC4M0E6ZAnEADrKaOd54QqoS/alzo+quYK4ba0dqOtg1st/MLHENkNv8nFsS/pmq428aySxOPxjCUnlKd1YDz5BevaFPVRPu1509T4a1MLE8fZ7oJz2FgH2zkXSDEwd+bEEalNOKoaBOPGa0uT6+tzVRcAd/lXueQm+A2U7ygk9/u+l5QL7it3BOlJrKSEU0VcnX/sagwBHM1/2DE2MHzHS2YkSITsAX7ltY48MS+kvzwGC+nnn80pg0tbddeY=
  - secure: ZRIX/OFWkuq7xQjGP9bkEWbhK4Rsh2TQ3sLeOpkfgnLNlUrw/pqYQhfqZ6T3pL3YpkdMlmTcgO5uuQ5UGmUfQBFRNDPXwYcriIp3KnArbUr3CsZOQsgR/QtkpPc+jLJFd4SbKcMa9G7Bw70ZMUHQfWDHH9cUhBjVA7ZESG4y1AuDDNhrn38/ANgEjSYB4SSMFu8N6y4GqukGPNhd2M0qQZPiRJTYwwgiuACON+lGwEhFcGXxb6wPgXsBNlzD6Ua4RL5cWLEZkOo0IicsUaoYFXNZpUPLQu/AjX5Ep7RUIG6B81lRgE5gP/zBLGPQN9/gDxQexvJysrv90yOZpvxN8xDwuqv80IShQHBnrHphmfCTkO2MsHfUNsB555hZ81E0cbf9Pse8GMI50uJ3Go9hdRUf8ZZuYVe5eoNm8GX/nL1Nwq88G+KoYOgabhUbNHjyT40SNHau2kT73Ot2GTP4MeMJBd4cGqVC4iKmmoTu78LMDDiFJDQDdzuNT8jCrcLPvU4AAUxkBta1ZxDnJlvLUUggdtqM+sc5VmNnAh238LAltKz+pjDL8MXcqO146dfcAQAmED0Fxk+W6gNt1w3/CEJodEeBsc7BZ9ZH1XUwup6IFpxJy3dCSzxP26vxjMaZNrB9hOI/mhWxdEsTykEdCh+n54NcyuymnXuCPLi9lO8=
